//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupWizard4PS.PersGebrInstellingRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", ConfigurationName="PersGebrInstellingRef.PersGebrInstelling_Port")]
    public interface PersGebrInstelling_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result ReadByRecId(StartupWizard4PS.PersGebrInstellingRef.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result> ReadByRecIdAsync(StartupWizard4PS.PersGebrInstellingRef.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result ReadMultiple(StartupWizard4PS.PersGebrInstellingRef.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result> ReadMultipleAsync(StartupWizard4PS.PersGebrInstellingRef.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result IsUpdated(StartupWizard4PS.PersGebrInstellingRef.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result> IsUpdatedAsync(StartupWizard4PS.PersGebrInstellingRef.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result GetRecIdFromKey(StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/persgebrinstelling:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling")]
    public partial class PersGebrInstelling : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string user_IDField;
        
        private string profile_IDField;
        
        private int language_IDField;
        
        private bool language_IDFieldSpecified;
        
        private int locale_IDField;
        
        private bool locale_IDFieldSpecified;
        
        private string time_ZoneField;
        
        private string companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
                this.RaisePropertyChanged("User_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Profile_ID {
            get {
                return this.profile_IDField;
            }
            set {
                this.profile_IDField = value;
                this.RaisePropertyChanged("Profile_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Language_ID {
            get {
                return this.language_IDField;
            }
            set {
                this.language_IDField = value;
                this.RaisePropertyChanged("Language_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Language_IDSpecified {
            get {
                return this.language_IDFieldSpecified;
            }
            set {
                this.language_IDFieldSpecified = value;
                this.RaisePropertyChanged("Language_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Locale_ID {
            get {
                return this.locale_IDField;
            }
            set {
                this.locale_IDField = value;
                this.RaisePropertyChanged("Locale_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Locale_IDSpecified {
            get {
                return this.locale_IDFieldSpecified;
            }
            set {
                this.locale_IDFieldSpecified = value;
                this.RaisePropertyChanged("Locale_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Time_Zone {
            get {
                return this.time_ZoneField;
            }
            set {
                this.time_ZoneField = value;
                this.RaisePropertyChanged("Time_Zone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling")]
    public partial class PersGebrInstelling_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersGebrInstelling_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersGebrInstelling_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling")]
    public enum PersGebrInstelling_Fields {
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Profile_ID,
        
        /// <remarks/>
        Language_ID,
        
        /// <remarks/>
        Locale_ID,
        
        /// <remarks/>
        Time_Zone,
        
        /// <remarks/>
        Company,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling PersGebrInstelling;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling PersGebrInstelling) {
            this.PersGebrInstelling = PersGebrInstelling;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/persgebrinstelling", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersGebrInstelling_PortChannel : StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersGebrInstelling_PortClient : System.ServiceModel.ClientBase<StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port>, StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port {
        
        public PersGebrInstelling_PortClient() {
        }
        
        public PersGebrInstelling_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersGebrInstelling_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersGebrInstelling_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersGebrInstelling_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.ReadByRecId(StartupWizard4PS.PersGebrInstellingRef.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling ReadByRecId(string recId) {
            StartupWizard4PS.PersGebrInstellingRef.ReadByRecId inValue = new StartupWizard4PS.PersGebrInstellingRef.ReadByRecId();
            inValue.recId = recId;
            StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result retVal = ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).ReadByRecId(inValue);
            return retVal.PersGebrInstelling;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result> StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.ReadByRecIdAsync(StartupWizard4PS.PersGebrInstellingRef.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            StartupWizard4PS.PersGebrInstellingRef.ReadByRecId inValue = new StartupWizard4PS.PersGebrInstellingRef.ReadByRecId();
            inValue.recId = recId;
            return ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.ReadMultiple(StartupWizard4PS.PersGebrInstellingRef.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling[] ReadMultiple(StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Filter[] filter, string bookmarkKey, int setSize) {
            StartupWizard4PS.PersGebrInstellingRef.ReadMultiple inValue = new StartupWizard4PS.PersGebrInstellingRef.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result retVal = ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result> StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.ReadMultipleAsync(StartupWizard4PS.PersGebrInstellingRef.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.ReadMultiple_Result> ReadMultipleAsync(StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Filter[] filter, string bookmarkKey, int setSize) {
            StartupWizard4PS.PersGebrInstellingRef.ReadMultiple inValue = new StartupWizard4PS.PersGebrInstellingRef.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.IsUpdated(StartupWizard4PS.PersGebrInstellingRef.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            StartupWizard4PS.PersGebrInstellingRef.IsUpdated inValue = new StartupWizard4PS.PersGebrInstellingRef.IsUpdated();
            inValue.Key = Key;
            StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result retVal = ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result> StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.IsUpdatedAsync(StartupWizard4PS.PersGebrInstellingRef.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.IsUpdated_Result> IsUpdatedAsync(string Key) {
            StartupWizard4PS.PersGebrInstellingRef.IsUpdated inValue = new StartupWizard4PS.PersGebrInstellingRef.IsUpdated();
            inValue.Key = Key;
            return ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.GetRecIdFromKey(StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey inValue = new StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey();
            inValue.Key = Key;
            StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result retVal = ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result> StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port.GetRecIdFromKeyAsync(StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey inValue = new StartupWizard4PS.PersGebrInstellingRef.GetRecIdFromKey();
            inValue.Key = Key;
            return ((StartupWizard4PS.PersGebrInstellingRef.PersGebrInstelling_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
