//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupWizard4PS.NST100TestContosoProfielOverzichtRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", ConfigurationName="NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port")]
    public interface ProfielOverzicht_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result Read(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result> ReadAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result ReadByRecId(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result> ReadByRecIdAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result ReadMultiple(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result> ReadMultipleAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result IsUpdated(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result> IsUpdatedAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result GetRecIdFromKey(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/profieloverzicht:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht")]
    public partial class ProfielOverzicht : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string profile_IDField;
        
        private string descriptionField;
        
        private int role_Center_IDField;
        
        private bool role_Center_IDFieldSpecified;
        
        private bool default_Role_CenterField;
        
        private bool default_Role_CenterFieldSpecified;
        
        private bool disable_PersonalizationField;
        
        private bool disable_PersonalizationFieldSpecified;
        
        private bool use_Record_NotesField;
        
        private bool use_Record_NotesFieldSpecified;
        
        private string record_NotebookField;
        
        private bool use_Page_NotesField;
        
        private bool use_Page_NotesFieldSpecified;
        
        private string page_NotebookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Profile_ID {
            get {
                return this.profile_IDField;
            }
            set {
                this.profile_IDField = value;
                this.RaisePropertyChanged("Profile_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Role_Center_ID {
            get {
                return this.role_Center_IDField;
            }
            set {
                this.role_Center_IDField = value;
                this.RaisePropertyChanged("Role_Center_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Role_Center_IDSpecified {
            get {
                return this.role_Center_IDFieldSpecified;
            }
            set {
                this.role_Center_IDFieldSpecified = value;
                this.RaisePropertyChanged("Role_Center_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Default_Role_Center {
            get {
                return this.default_Role_CenterField;
            }
            set {
                this.default_Role_CenterField = value;
                this.RaisePropertyChanged("Default_Role_Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Default_Role_CenterSpecified {
            get {
                return this.default_Role_CenterFieldSpecified;
            }
            set {
                this.default_Role_CenterFieldSpecified = value;
                this.RaisePropertyChanged("Default_Role_CenterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Disable_Personalization {
            get {
                return this.disable_PersonalizationField;
            }
            set {
                this.disable_PersonalizationField = value;
                this.RaisePropertyChanged("Disable_Personalization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Disable_PersonalizationSpecified {
            get {
                return this.disable_PersonalizationFieldSpecified;
            }
            set {
                this.disable_PersonalizationFieldSpecified = value;
                this.RaisePropertyChanged("Disable_PersonalizationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Use_Record_Notes {
            get {
                return this.use_Record_NotesField;
            }
            set {
                this.use_Record_NotesField = value;
                this.RaisePropertyChanged("Use_Record_Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Record_NotesSpecified {
            get {
                return this.use_Record_NotesFieldSpecified;
            }
            set {
                this.use_Record_NotesFieldSpecified = value;
                this.RaisePropertyChanged("Use_Record_NotesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Record_Notebook {
            get {
                return this.record_NotebookField;
            }
            set {
                this.record_NotebookField = value;
                this.RaisePropertyChanged("Record_Notebook");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Use_Page_Notes {
            get {
                return this.use_Page_NotesField;
            }
            set {
                this.use_Page_NotesField = value;
                this.RaisePropertyChanged("Use_Page_Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Page_NotesSpecified {
            get {
                return this.use_Page_NotesFieldSpecified;
            }
            set {
                this.use_Page_NotesFieldSpecified = value;
                this.RaisePropertyChanged("Use_Page_NotesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Page_Notebook {
            get {
                return this.page_NotebookField;
            }
            set {
                this.page_NotebookField = value;
                this.RaisePropertyChanged("Page_Notebook");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht")]
    public partial class ProfielOverzicht_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProfielOverzicht_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProfielOverzicht_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht")]
    public enum ProfielOverzicht_Fields {
        
        /// <remarks/>
        Profile_ID,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Role_Center_ID,
        
        /// <remarks/>
        Default_Role_Center,
        
        /// <remarks/>
        Disable_Personalization,
        
        /// <remarks/>
        Use_Record_Notes,
        
        /// <remarks/>
        Record_Notebook,
        
        /// <remarks/>
        Use_Page_Notes,
        
        /// <remarks/>
        Page_Notebook,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public string Profile_ID;
        
        public Read() {
        }
        
        public Read(string Profile_ID) {
            this.Profile_ID = Profile_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht ProfielOverzicht;
        
        public Read_Result() {
        }
        
        public Read_Result(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht ProfielOverzicht) {
            this.ProfielOverzicht = ProfielOverzicht;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht ProfielOverzicht;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht ProfielOverzicht) {
            this.ProfielOverzicht = ProfielOverzicht;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/profieloverzicht", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProfielOverzicht_PortChannel : StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfielOverzicht_PortClient : System.ServiceModel.ClientBase<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port>, StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port {
        
        public ProfielOverzicht_PortClient() {
        }
        
        public ProfielOverzicht_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfielOverzicht_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfielOverzicht_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfielOverzicht_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.Read(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read request) {
            return base.Channel.Read(request);
        }
        
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht Read(string Profile_ID) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read();
            inValue.Profile_ID = Profile_ID;
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result retVal = ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).Read(inValue);
            return retVal.ProfielOverzicht;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result> StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.ReadAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read_Result> ReadAsync(string Profile_ID) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.Read();
            inValue.Profile_ID = Profile_ID;
            return ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.ReadByRecId(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht ReadByRecId(string recId) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId();
            inValue.recId = recId;
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result retVal = ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).ReadByRecId(inValue);
            return retVal.ProfielOverzicht;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result> StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.ReadByRecIdAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadByRecId();
            inValue.recId = recId;
            return ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.ReadMultiple(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht[] ReadMultiple(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Filter[] filter, string bookmarkKey, int setSize) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result retVal = ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result> StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.ReadMultipleAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple_Result> ReadMultipleAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Filter[] filter, string bookmarkKey, int setSize) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.IsUpdated(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated();
            inValue.Key = Key;
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result retVal = ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result> StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.IsUpdatedAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated_Result> IsUpdatedAsync(string Key) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.IsUpdated();
            inValue.Key = Key;
            return ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.GetRecIdFromKey(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey();
            inValue.Key = Key;
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result retVal = ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result> StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port.GetRecIdFromKeyAsync(StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey inValue = new StartupWizard4PS.NST100TestContosoProfielOverzichtRef.GetRecIdFromKey();
            inValue.Key = Key;
            return ((StartupWizard4PS.NST100TestContosoProfielOverzichtRef.ProfielOverzicht_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
